<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Npgsql" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\gRPC\Common\Common.csproj" />
		<ProjectReference Include="..\..\..\Shared\Helpers\Helpers.csproj" />
		<ProjectReference Include="..\Profile.Domain\Profile.Domain.csproj" />
	</ItemGroup>

</Project>
