syntax = "proto3";

option csharp_namespace = "Contracts";

package corHrmm;

service CorHrmmService {
  rpc GetJgStep (CorHrmmRqst) returns (CorHrmmRes);
  rpc GetListJgStep (CorHrmmListRqst) returns (CorHrmmListRes);
  rpc GetJobGrade (CorHrmmRqst) returns (CorHrmmRes);
  rpc GetListJobGrade (CorHrmmListRqst) returns (CorHrmmListRes);
  rpc GetPosition (CorHrmmRqst) returns (CorHrmmRes);
  rpc GetListPosition (CorHrmmListRqst) returns (CorHrmmListRes);
  rpc GetPosReq (CorHrmmRqst) returns (PosReqRes);
}

message PosReqRes {
  string Id = 1;
  string PositionId = 2;
  string Gender = 3;
  string ProfessionType = 4;
  string SaturdayWorkOption = 5;
  string SundayWorkOption = 6;
  string WorkingHours = 7;
}

message CorHrmmList {
  string Id = 1;
  string Name = 2;  
}

message CorHrmmListAm {
  string Id = 1;
  string Name = 2;
  string NameAm = 3;
}

message CorHrmmListRqst {}

message CorHrmmRqst {
  string Id = 1;
}

message CorHrmmListRes { 
  repeated CorHrmmList Res = 1; 
}

message CorHrmmListResAm { 
  repeated CorHrmmListAm Res = 1; 
}

message CorHrmmRes { 
  CorHrmmList Res = 1;
}

message CorHrmmResAm { 
  CorHrmmListAm Res = 1;
}