syntax = "proto3";

option csharp_namespace = "Contracts";

package corModule;

service CorModuleService {
  rpc GetDept (CorModuleRqst) returns (CorModuleResAm);
  rpc GetListDept (CorModuleListRqst) returns (CorModuleListResAm);
  rpc GetFiscalYear (CorModuleRqst) returns (CorModuleRes);
  rpc GetFiscYearDesc (CorModuleRqst) returns (ActFiscalYear);
  rpc GetListFiscalYear (CorModuleListRqst) returns (CorModuleListRes);
  rpc GetActiveFiscal (CorModuleListRqst) returns (ActFiscalYear);
  rpc GetHoDay (CorModuleRqst) returns (HoDayRes);
  rpc GetListHoDay (CorModuleListRqst) returns (HoDayListRes);
  rpc GetPeriod (CorModuleRqst) returns (PeriodRes);
  rpc GetListPeriod (CorModuleListRqst) returns (PeriodListRes);
  rpc GetDbc (CorModuleRqst) returns (DbcRes);
  rpc GetListDbc (CorModuleListRqst) returns (DbcListRes);

  rpc GetBranch (CorModuleRqst) returns (CorModuleResAm);
  rpc GetListBranch (CorModuleListRqst) returns (CorModuleListResAm);
  rpc GetCompany (CorModuleRqst) returns (CorModuleResAm);
  rpc GetListCompany (CorModuleListRqst) returns (CorModuleListResAm);
}

message DbcRes {
  string DeptId = 1;
  string BranchId = 2;  
  string CompId = 3;
}

message DbcListRes { 
  repeated DbcRes Res = 1; 
}

message PeriodRes {
  string Id = 1;
  string Name = 2;  
  string Quarter = 3;
  string FiscalYearId = 4;
}

message PeriodListRes { 
  repeated PeriodRes Res = 1; 
}

message HoDayRes {
  string Id = 1;
  string Name = 2;  
  string Date = 3;  
  bool IsPublic = 4;
  string FiscalYearId = 5;
}

message HoDayListRes { 
  repeated HoDayRes Res = 1; 
}

message ActFiscalYear {
  string Id = 1;
  string Name = 2;  
  string StartDate = 3;  
  string EndDate = 4;  
}

message CorModList {
  string Id = 1;
  string Name = 2;  
}

message CorModListAm {
  string Id = 1;
  string Name = 2;
  string NameAm = 3;
}

message CorModuleListRqst {}

message CorModuleRqst {
  string Id = 1;
}

message CorModuleResAm { 
  CorModListAm Res = 1;
}

message CorModuleRes { 
  CorModList Res = 1;
}

message CorModuleListResAm { 
  repeated CorModListAm Res = 1; 
}

message CorModuleListRes { 
  repeated CorModList Res = 1; 
}