syntax = "proto3";

option csharp_namespace = "Contracts";

package hrmProfile;

service HrmProfileService {
  rpc GetEmpCode (HrmProRqst) returns (HrmProResCode);
  rpc GetEmp (HrmProRqst) returns (HrmProRes);
  rpc GetPosEmp (HrmProRqst) returns (EmpPosRes);
  rpc GetListEmp (HrmProListRqst) returns (HrmProListRes);
  rpc GetListEmpPolicy (HrmProListRqst) returns (HrmProListPlcy);
  rpc GetEmpPolicy (HrmProRqst) returns (HrmEmpPlcy);
}

message HrmEmpPlcy {
  string Id = 1;
  string Name = 2;
  string SerYear = 3;
  string EmpType = 4;
  string WorkAr = 5;
  string Gender = 6;
  string Jg = 7;
}

message EmpPosRes {
  string Id = 1;
  string SaturdayWorkOption = 2;
  string SundayWorkOption = 3;
  string PositionId = 4;
}

message HrmProList {
  string Id = 1;
  string Name = 2;  
}

message HrmProListAm {
  string Id = 1;
  string Name = 2;
  string NameAm = 3;
}

message HrmProListRqst {}

message HrmProRqst {
  string Id = 1;
}

message HrmProListPlcy { 
  repeated HrmEmpPlcy Res = 1; 
}

message HrmProListRes { 
  repeated HrmProList Res = 1; 
}

message HrmProListResAm { 
  repeated HrmProListAm Res = 1; 
}

message HrmProRes { 
  HrmProList Res = 1;
}

message HrmProResAm { 
  HrmProListAm Res = 1;
}

message HrmProResCode { 
  string Code = 1;
}