syntax = "proto3";

option csharp_namespace = "Contracts";

package hrmProfile;

service HrmProfileService {
  rpc GetEmpCode (HrmProRqst) returns (HrmProResCode);
  rpc GetEmpCodeList (HrmProListRqst) returns (HrmProResCodeList);
  rpc GetEmp (HrmProRqst) returns (HrmProRes);
  rpc GetListEmp (HrmProListRqst) returns (HrmProListRes);
  rpc GetPosEmp (HrmProRqst) returns (EmpPosRes);
  rpc GetEmpId (HrmProRqst) returns (HrmEmpId);
  rpc GetListEmpId (HrmProListRqst) returns (HrmListEmpId);
  rpc GetAdminEmpList (HrmProListRqst) returns (AdminEmpList);
  rpc GetEmpNameList (HrmProListRqst) returns (HrmProListResAm);

  rpc GetListEmpPolicy (HrmProListRqst) returns (HrmProListPlcy);
  rpc GetDeptEmpPolicy (HrmProRqst) returns (HrmProListPlcy);
  rpc GetBraEmpPolicy (HrmProRqst) returns (HrmProListPlcy);
  rpc GetEmpPolicy (HrmProRqst) returns (HrmEmpPlcy);
  rpc GetGendEmpPolicy (HrmProRqst) returns (HrmProListPlcy);
  rpc GetEmpBasicInfo (HrmProRqst) returns (EmpBasicInfoRes);
}

message EmpBasicInfoRes {
  string Id = 1;
  string EmpFullName = 2;
  string EmpFullNameAm = 3;
  string Code = 4;
  string Gender = 5;
  string EmpState = 6;
  string Branch = 7;
  string Department = 8;
  string Position = 9;
  string JobGrade = 10;
  string EmpType = 11;
  string EmpNature = 12;
  string WorkArr = 13;
}

message AdminEmp {
  string Id = 1;
  string Name = 2;
  string NameAm = 3;
  string Gender = 4;
  string Code = 5;
  string Branch = 6;
  string Dept = 7;
  string Position = 8;
  string Status = 9;
}

message HrmEmpId {
  string Id = 1;
  string PositionId = 2;
  string DeptId = 3;
  string BranchId = 4;
  string CompanyId = 5;
  string JgStepId = 6;
  string JgId = 7;
}

message HrmEmpPlcy {
  string Id = 1;
  string Name = 2;
  string SerYear = 3;
  string EmpType = 4;
  string WorkAr = 5;
  string Gender = 6;
  string Jg = 7;
}

message EmpPosRes {
  string Id = 1;
  string SaturdayWorkOption = 2;
  string SundayWorkOption = 3;
  string PositionId = 4;
}

message HrmProList {
  string Id = 1;
  string Name = 2;
  string NameAm = 3;
}



message HrmProListRqst {}

message HrmProRqst {
  string Id = 1;
}

message HrmListEmpId {
  repeated HrmEmpId Res = 1;
}

message AdminEmpList {
  repeated AdminEmp Res = 1;
}

message HrmProListPlcy {
  repeated HrmEmpPlcy Res = 1;
}

message HrmProListRes {
  repeated HrmProList Res = 1;
}

message HrmProListResAm {
  repeated HrmProListAm Res = 1;
}

message HrmProRes {
  HrmProList Res = 1;
}

message HrmProResAm {
  HrmProListAm Res = 1;
}

message HrmProResCode {
  string Id = 1;
  string Name = 2;
  string NameAm = 3;
  string Code = 4;
}
message HrmProListAm {
  string Id = 1;
  string Name = 2;
  string NameAm = 3;
}
message HrmProResCodeList {
  repeated HrmProResCode Res = 1;
}