syntax = "proto3";

option csharp_namespace = "Contracts";

package lup;

service LupService {
  rpc GetEduLevel (LupRqst) returns (LupRes);
  rpc GetListEduLevel (LupListRqst) returns (LupListRes);
  rpc GetRel (LupRqst) returns (LupRes);
  rpc GetRelList (LupListRqst) returns (LupListRes);
}

message LupList {
  string Id = 1;
  string Name = 2;  
}

message LupListAm {
  string Id = 1;
  string Name = 2;
  string NameAm = 3;
}

message LupListRqst {}

message LupListRes { 
  repeated LupList Res = 1; 
}

message LupRqst {
  string Id = 1;
}

message LupRes { 
  LupList Res = 1;
}