<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.AspNetCore" />
		<PackageReference Include="Grpc.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Contracts\Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="..\Contracts\auth.proto" GrpcServices="Both" />
		<Protobuf Include="..\Contracts\corModule.proto" GrpcServices="Both" />
		<Protobuf Include="..\Contracts\corHrmm.proto" GrpcServices="Both" />
		<Protobuf Include="..\Contracts\hrmProfile.proto" GrpcServices="Both" />
		<Protobuf Include="..\Contracts\finance.proto" GrpcServices="Both" />  <!-- ? ADD THIS -->
		<Protobuf Include="..\Contracts\crm.proto" GrpcServices="Both" />  <!-- ? ADD THIS -->
		<Protobuf Include="..\Contracts\project.proto" GrpcServices="Both" />  <!-- ? ADD THIS -->

	</ItemGroup>

   </Project>