<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.1.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>0abf4ba6-797d-4763-b9ea-a578c07482fd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Svc.Auth\Svc.Auth.csproj" />
    <ProjectReference Include="..\Svc.Core\Cor.HRMM\Cor.HRMM.csproj" />
    <ProjectReference Include="..\Svc.Core\Cor.Module\Cor.Module.csproj" />
    <ProjectReference Include="..\Svc.Gateway\Svc.Gateway.csproj" />
    <ProjectReference Include="..\Svc.HRM\HRM.Leave\Leave.API\Leave.API.csproj" />
    <ProjectReference Include="..\Svc.HRM\HRM.Profile\Profile.API\Profile.API.csproj" />
    <ProjectReference Include="..\Svc.HRM\HRM.Recruit\Recruit.API\Recruit.API.csproj" />
  </ItemGroup>

</Project>
