apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: erp-system
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ServiceUrls__CoreModuleApi: "http://core-api:80"
  ServiceUrls__CoreHRMMApi: "http://core-hrmm-api:80"
  ServiceUrls__HRMProApi: "http://hrm-pro-api:80"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "guest"