apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: erp-system
type: Opaque
data:
  # Base64 encoded values
  # echo -n "postgres" | base64
  authMgrCon: "SG9zdD1hdXRoLWRiO1BvcnQ9NTQzMjtEYXRhYmFzZT1BdXRoLk1ncjtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1Sb290QDEyMw=="
  RabbitMQ__Password: "Z3Vlc3Q="