<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Hosted\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Quartz" Version="3.15.1" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.15.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Leave.App\Leave.App.csproj" />
  </ItemGroup>

</Project>
