<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<Folder Include="Extensions\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Serilog" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Leave.App\Leave.App.csproj" />
	</ItemGroup>

</Project>
