<Project Sdk="Microsoft.NET.Sdk.Web">
	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
		<PackageReference Include="Dapper" />
		<PackageReference Include="EthiopianCalendar" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Scalar.AspNetCore" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
		<PackageReference Include="Grpc.Tools">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\gRPC\Auth.Security\Auth.Security.csproj" />
	  <ProjectReference Include="..\..\RST_ERP.ServiceDefaults\RST_ERP.ServiceDefaults.csproj" />
	</ItemGroup>
</Project>
