<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Dapper" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		 <PackageReference Include="Microsoft.Extensions.Configuration" />
            <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
            <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
		<PackageReference Include="Npgsql" />
		<PackageReference Include="SixLabors.ImageSharp" />
		<PackageReference Include="StackExchange.Redis" />
	</ItemGroup>

   <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </None>
    </ItemGroup></Project>
