<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Dapper" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Npgsql" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="SixLabors.ImageSharp" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Profile.App\Profile.App.csproj" />
	</ItemGroup>

</Project>
