<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Dapper" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Serilog" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Profile.App\Profile.App.csproj" />
	</ItemGroup>

</Project>
