// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Svc.HRM.Payroll.Persistence;

#nullable disable

namespace Svc.HRM.Payroll.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    partial class PayrollDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Svc.HRM.Payroll.Models.Entities.LocalEmployeeSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateMod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Deductions")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HousingAllowance")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MealAllowance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MedicalAllowance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OtherAllowances")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PensionContribution")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SalaryStructureId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TransportAllowance")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SalaryStructureId");

                    b.HasIndex("EmployeeId", "IsActive");

                    b.ToTable("EmployeeSalaries");
                });

            modelBuilder.Entity("Svc.HRM.Payroll.Models.Entities.LocalPayrollEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BonusPay")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CommissionPay")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateMod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysAbsent")
                        .HasColumnType("integer");

                    b.Property<int>("DaysWorked")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GrossPay")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HousingAllowance")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MealAllowance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MedicalAllowance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("OtherAllowances")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OtherDeductions")
                        .HasColumnType("numeric");

                    b.Property<int>("OvertimeHours")
                        .HasColumnType("integer");

                    b.Property<decimal>("OvertimePay")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PayrollRunId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PensionContribution")
                        .HasColumnType("numeric");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TransportAllowance")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PayrollRunId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("PayrollEmployees");
                });

            modelBuilder.Entity("Svc.HRM.Payroll.Models.Entities.LocalPayrollRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateMod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("PayPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PayPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayrollStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalEmployees")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalGrossPay")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalNetPay")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalTaxes")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PayPeriodEnd");

                    b.HasIndex("PayPeriodStart");

                    b.HasIndex("PayrollStatus");

                    b.ToTable("PayrollRuns");
                });

            modelBuilder.Entity("Svc.HRM.Payroll.Models.Entities.LocalPayslip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateMod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("GrossPay")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<Guid>("PayrollEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayslipNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAllowances")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PayrollEmployeeId");

                    b.HasIndex("PayslipNumber")
                        .IsUnique();

                    b.ToTable("Payslips");
                });

            modelBuilder.Entity("Svc.HRM.Payroll.Models.Entities.LocalSalaryStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateMod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Deductions")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("HousingAllowance")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MealAllowance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MedicalAllowance")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OtherAllowances")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PensionContribution")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TransportAllowance")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SalaryStructures");
                });

            modelBuilder.Entity("Svc.HRM.Payroll.Models.Entities.LocalTaxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateMod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeductibleAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxIncome")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinIncome")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric");

                    b.Property<string>("TaxYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaxYear", "IsActive");

                    b.ToTable("TaxRates");
                });

            modelBuilder.Entity("Svc.HRM.Payroll.Models.Entities.LocalEmployeeSalary", b =>
                {
                    b.HasOne("Svc.HRM.Payroll.Models.Entities.LocalSalaryStructure", "SalaryStructure")
                        .WithMany()
                        .HasForeignKey("SalaryStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalaryStructure");
                });

            modelBuilder.Entity("Svc.HRM.Payroll.Models.Entities.LocalPayrollEmployee", b =>
                {
                    b.HasOne("Svc.HRM.Payroll.Models.Entities.LocalPayrollRun", "PayrollRun")
                        .WithMany("PayrollEmployees")
                        .HasForeignKey("PayrollRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayrollRun");
                });

            modelBuilder.Entity("Svc.HRM.Payroll.Models.Entities.LocalPayslip", b =>
                {
                    b.HasOne("Svc.HRM.Payroll.Models.Entities.LocalPayrollEmployee", "PayrollEmployee")
                        .WithMany()
                        .HasForeignKey("PayrollEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayrollEmployee");
                });

            modelBuilder.Entity("Svc.HRM.Payroll.Models.Entities.LocalPayrollRun", b =>
                {
                    b.Navigation("PayrollEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
